version: '3'
services:

    web:
      build: ./
      container_name: spa
      volumes:
        - ./spa:/usr/src/app
      depends_on:
        - mysql
      expose:
        - "8000"
      command: >
        sh -c "python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"

    mysql:
      image: mysql:5.7.22
      container_name: db
      restart: unless-stopped 
      environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: 111
        MYSQL_DATABASE: spa_app
        # MYSQL_ROOT_HOST: nodejs
      ports:
        - "3306:3306"
      volumes:     
        - dbdata:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    
    nginx:
      container_name: nginx
      image: nginx:1.13
      restart: always
      ports:
        - 8081:80
        - 443:443
      volumes:
        - ./docker/nginx/conf.d:/etc/nginx/conf.d

volumes:
  dbdata:
  
