# Generated by Django 2.2.3 on 2019-09-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='app_users',
        ),
    ]
