# Generated by Django 2.2.3 on 2019-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
