# Generated by Django 2.2.3 on 2019-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='mobile',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
